services:
  wordpress:
    build:
      context: .
      args:
        WORDPRESS_IMAGE: wordpress:7.0.0-php8.5-apache
        SQLITE_DATABASE_INTEGRATION_COMMIT: e5513936c800f14b6795e7fce71505afad331b11
        WORDPRESS_HTTP_PORT: 7860
    restart: always
    ports:
      - "7860:7860"
    volumes:
      - ./wordpress:/var/www/html
