services:
  wordpress:
    build:
      context: .
      args:
        WORDPRESS_IMAGE: ${WORDPRESS_IMAGE:-wordpress:apache}
        SQLITE_DATABASE_INTEGRATION_COMMIT: ${SQLITE_DATABASE_INTEGRATION_COMMIT:-latest}
        WORDPRESS_HTTP_PORT: ${WORDPRESS_HTTP_PORT:-7860}
        UPDATE_CACHE_BUST: ${UPDATE_CACHE_BUST:-manual}
    restart: always
    ports:
      - "${WORDPRESS_HTTP_PORT:-7860}:${WORDPRESS_HTTP_PORT:-7860}"
    volumes:
      - ./wordpress:/var/www/html
